
# Generated by CodiumAI

import pytest

class TestMain:

    #  Returns a JSON object with a "message" key and value "Hello World"
    @pytest.mark.asyncio
    async def test_returns_hello_world(self):
        response = await app.get("/")
        assert response.status_code == 200
        assert response.json() == {"message": "Hello World"}

    #  None
    @pytest.mark.asyncio
    async def test_returns_none(self):
        response = await app.get("/")
        assert response.status_code == 200
        assert response.json() is None

    #  Returns a JSON object with a "message" key and a value that is not "Hello World"
    @pytest.mark.asyncio
    async def test_returns_not_hello_world(self):
        response = await app.get("/")
        assert response.status_code == 200
        assert response.json() != {"message": "Hello World"}

    #  Returns a JSON object with additional keys and values
    @pytest.mark.asyncio
    async def test_returns_additional_keys_values(self):
        response = await app.get("/")
        assert response.status_code == 200
        assert "message" in response.json()
        assert "additional_key" in response.json()

    #  Returns a JSON object with missing keys
    @pytest.mark.asyncio
    async def test_returns_missing_keys(self):
        response = await app.get("/")
        assert response.status_code == 200
        assert "message" in response.json()
        assert "missing_key" not in response.json()
