
# Generated by CodiumAI
from fastapi.testclient import TestClient
import pytest

from main import app

client = TestClient(app)


class TestMain:

    #  Returns a JSON object with a "message" key and value "Hello World"
    @pytest.mark.asyncio
    async def test_returns_hello_world(self):
        response = client.get("/")
        assert response.status_code == 200
        assert response.json() == {"message": "Hello World"}
